-- =============================================================================
-- Big Matt's BBQ — Migration 0012 (retroactive capture)
-- Captures `public.attribution_sources` exactly as it exists live on
-- production today: table, RLS enablement, one public-read policy, and the
-- 8 real attribution option rows. This was applied directly to production on
-- 2026-08-28 (tracked on prod as Supabase migration version 20260828181057,
-- name `create_attribution_sources`), but was never committed to this repo —
-- captured now (issue #14) so the repo becomes the true source of truth.
--
-- Unlike 0010/0011's menu_costing captures, this one *is* part of the
-- storefront app — it backs the checkout attribution feature shipped in
-- Phase 12 (docs/checkout-attribution.md). The seeded rows below are
-- catalog/config data, not customer data, and are safe to ship as-is.
--
-- The content below is copied verbatim, byte-for-byte, from production's own
-- `supabase_migrations.schema_migrations.statements` column for this version.
-- =============================================================================

create table public.attribution_sources (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label text not null,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  requires_detail boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.attribution_sources enable row level security;

create policy "Public can read active attribution sources"
on public.attribution_sources
for select
to anon, authenticated
using (is_active = true);

insert into public.attribution_sources (code, label, is_active, sort_order, requires_detail)
values
  ('referral', 'Friend, family, or coworker', true, 10, false),
  ('facebook', 'Facebook', true, 20, false),
  ('instagram', 'Instagram', true, 30, false),
  ('google', 'Google or another search engine', true, 40, false),
  ('ai', 'ChatGPT or another AI', true, 50, true),
  ('event', 'Saw Big Matt''s BBQ at an event', true, 60, true),
  ('returning', 'Previous customer', true, 70, false),
  ('other', 'Other', true, 80, true);
