-- =============================================================================
-- Big Matt's BBQ — Migration 0013 (retroactive capture)
-- Captures the `sca` schema's tables, RLS enablement, foreign keys, and
-- indexes exactly as they exist live on production today. This schema backs
-- the SCA Tracker feature (v2.0 milestone, Phases 9-11).
--
-- This schema was NEVER tracked by Supabase's own migration system on
-- production — it was created out-of-band (STATE.md Phase 09 notes: "shipped
-- via Supabase CLI, no MCP tool access this session"). This file, plus
-- 0014_sca_trigger_functions.sql and 0015_sca_rls_policies.sql, reconstruct
-- it from a structural clone of the live schema (via `bigmattsbbq-test`'s
-- clone migrations), verified column-for-column, constraint-for-constraint
-- against production. Captured now as part of issue #14's full schema-drift
-- capture.
--
-- `create schema if not exists sca;` below is added by this capture — prod
-- never tracked the schema-creation statement on its own, since the schema
-- was created out-of-band. It is correct regardless of how the schema
-- originally came to exist.
--
-- Everything else in this file is copied verbatim from `bigmattsbbq-test`'s
-- `clone_sca_schema` and (for the indexes) `clone_indexes` migration
-- statements.
-- =============================================================================

create schema if not exists sca;

-- -----------------------------------------------------------------------------
-- Section 1: Tables
-- -----------------------------------------------------------------------------

CREATE TABLE sca.chef (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  auth_user_id uuid,
  username text NOT NULL,
  name text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  team_name text,
  CONSTRAINT chef_auth_user_id_key UNIQUE (auth_user_id),
  CONSTRAINT chef_name_check CHECK (btrim(name) <> ''::text),
  CONSTRAINT chef_pkey PRIMARY KEY (id),
  CONSTRAINT chef_team_name_not_blank CHECK (team_name IS NULL OR btrim(team_name) <> ''::text),
  CONSTRAINT chef_username_check CHECK (btrim(username) <> ''::text),
  CONSTRAINT chef_username_key UNIQUE (username)
);
ALTER TABLE sca.chef ENABLE ROW LEVEL SECURITY;

CREATE TABLE sca.competition (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  event_date date NOT NULL,
  city text,
  state text,
  elevation_ft integer,
  organizer text,
  notes text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT competition_name_check CHECK (btrim(name) <> ''::text),
  CONSTRAINT competition_pkey PRIMARY KEY (id)
);
ALTER TABLE sca.competition ENABLE ROW LEVEL SECURITY;

CREATE TABLE sca.cook (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  chef_id bigint NOT NULL,
  competition_id bigint,
  cooked_at timestamptz NOT NULL,
  steak_label text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT cook_pkey PRIMARY KEY (id)
);
ALTER TABLE sca.cook ENABLE ROW LEVEL SECURITY;

CREATE TABLE sca.cook_ai_review (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  cook_id bigint NOT NULL,
  review_type text,
  model text,
  prompt text,
  comments text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT cook_ai_review_comments_check CHECK (btrim(comments) <> ''::text),
  CONSTRAINT cook_ai_review_pkey PRIMARY KEY (id)
);
ALTER TABLE sca.cook_ai_review ENABLE ROW LEVEL SECURITY;

CREATE TABLE sca.cook_detail (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  cook_id bigint NOT NULL,
  trimmed_weight_oz numeric(5,2),
  steak_thickness_in numeric(4,2),
  starting_internal_temp_f numeric(5,2),
  grate_temp_f numeric(6,2),
  turn_interval_seconds integer,
  presentation_side_interval_count smallint,
  back_side_interval_count smallint,
  meatrix_pull_percent numeric(6,2),
  pull_internal_temp_f numeric(5,2),
  meatrix_peak_percent numeric(6,2),
  peak_internal_temp_f numeric(5,2),
  rest_duration_seconds integer,
  seasoning text,
  prep_notes text,
  cook_notes text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT cook_detail_back_side_interval_count_check CHECK (back_side_interval_count IS NULL OR back_side_interval_count >= 0),
  CONSTRAINT cook_detail_cook_id_key UNIQUE (cook_id),
  CONSTRAINT cook_detail_meatrix_peak_percent_check CHECK (meatrix_peak_percent IS NULL OR meatrix_peak_percent >= 0::numeric AND meatrix_peak_percent <= 100::numeric),
  CONSTRAINT cook_detail_meatrix_pull_percent_check CHECK (meatrix_pull_percent IS NULL OR meatrix_pull_percent >= 0::numeric AND meatrix_pull_percent <= 100::numeric),
  CONSTRAINT cook_detail_pkey PRIMARY KEY (id),
  CONSTRAINT cook_detail_presentation_side_interval_count_check CHECK (presentation_side_interval_count IS NULL OR presentation_side_interval_count >= 0),
  CONSTRAINT cook_detail_rest_duration_seconds_check CHECK (rest_duration_seconds IS NULL OR rest_duration_seconds >= 0),
  CONSTRAINT cook_detail_steak_thickness_in_check CHECK (steak_thickness_in IS NULL OR steak_thickness_in > 0::numeric),
  CONSTRAINT cook_detail_trimmed_weight_oz_check CHECK (trimmed_weight_oz IS NULL OR trimmed_weight_oz > 0::numeric),
  CONSTRAINT cook_detail_turn_interval_seconds_check CHECK (turn_interval_seconds IS NULL OR turn_interval_seconds > 0)
);
ALTER TABLE sca.cook_detail ENABLE ROW LEVEL SECURITY;

CREATE TABLE sca.cook_weather (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  cook_id bigint NOT NULL,
  observed_at timestamptz NOT NULL,
  temperature_f numeric(5,2),
  precipitation text,
  wind_speed_mph numeric(5,2),
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT cook_weather_pkey PRIMARY KEY (id),
  CONSTRAINT cook_weather_wind_speed_mph_check CHECK (wind_speed_mph IS NULL OR wind_speed_mph >= 0::numeric)
);
ALTER TABLE sca.cook_weather ENABLE ROW LEVEL SECURITY;

CREATE TABLE sca.score (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  cook_id bigint NOT NULL,
  ticket_number integer,
  appearance numeric(6,2),
  doneness numeric(6,2),
  texture numeric(6,2),
  taste numeric(6,2),
  overall_impression numeric(6,2),
  total_score numeric(7,2),
  placement integer,
  field_size integer,
  first_place_score numeric(7,2),
  score_notes text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT score_appearance_check CHECK (appearance IS NULL OR appearance >= 0::numeric),
  CONSTRAINT score_cook_id_key UNIQUE (cook_id),
  CONSTRAINT score_doneness_check CHECK (doneness IS NULL OR doneness >= 0::numeric),
  CONSTRAINT score_field_size_check CHECK (field_size IS NULL OR field_size > 0),
  CONSTRAINT score_first_place_score_check CHECK (first_place_score IS NULL OR first_place_score >= 0::numeric),
  CONSTRAINT score_overall_impression_check CHECK (overall_impression IS NULL OR overall_impression >= 0::numeric),
  CONSTRAINT score_pkey PRIMARY KEY (id),
  CONSTRAINT score_placement_check CHECK (placement IS NULL OR placement > 0),
  CONSTRAINT score_placement_within_field CHECK (placement IS NULL OR field_size IS NULL OR placement <= field_size),
  CONSTRAINT score_taste_check CHECK (taste IS NULL OR taste >= 0::numeric),
  CONSTRAINT score_texture_check CHECK (texture IS NULL OR texture >= 0::numeric),
  CONSTRAINT score_ticket_number_check CHECK (ticket_number IS NULL OR ticket_number >= 0),
  CONSTRAINT score_total_score_check CHECK (total_score IS NULL OR total_score >= 0::numeric)
);
ALTER TABLE sca.score ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------------------------------
-- Section 2: Foreign keys
-- -----------------------------------------------------------------------------

ALTER TABLE sca.chef ADD CONSTRAINT chef_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE sca.cook ADD CONSTRAINT cook_chef_id_fkey FOREIGN KEY (chef_id) REFERENCES sca.chef(id);
ALTER TABLE sca.cook ADD CONSTRAINT cook_competition_id_fkey FOREIGN KEY (competition_id) REFERENCES sca.competition(id);
ALTER TABLE sca.cook_ai_review ADD CONSTRAINT cook_ai_review_cook_id_fkey FOREIGN KEY (cook_id) REFERENCES sca.cook(id) ON DELETE CASCADE;
ALTER TABLE sca.cook_detail ADD CONSTRAINT cook_detail_cook_id_fkey FOREIGN KEY (cook_id) REFERENCES sca.cook(id) ON DELETE CASCADE;
ALTER TABLE sca.cook_weather ADD CONSTRAINT cook_weather_cook_id_fkey FOREIGN KEY (cook_id) REFERENCES sca.cook(id) ON DELETE CASCADE;
ALTER TABLE sca.score ADD CONSTRAINT score_cook_id_fkey FOREIGN KEY (cook_id) REFERENCES sca.cook(id) ON DELETE CASCADE;

-- -----------------------------------------------------------------------------
-- Section 3: Indexes
-- -----------------------------------------------------------------------------

create index competition_event_date_idx on sca.competition (event_date);
create index cook_chef_id_idx on sca.cook (chef_id);
create index cook_competition_id_idx on sca.cook (competition_id);
create index cook_ai_review_cook_id_idx on sca.cook_ai_review (cook_id);
create index cook_weather_cook_id_idx on sca.cook_weather (cook_id);
