-- =============================================================================
-- Big Matt's BBQ — Migration 0016 (retroactive capture)
-- Captures the `production` schema's tables, foreign keys, and indexes
-- exactly as they exist live on production today. Like `sca`, this schema
-- was never tracked by Supabase's own migration system on production and is
-- reconstructed here from `bigmattsbbq-test`'s `clone_production_schema` and
-- (for the indexes) `clone_indexes` migration statements, verified
-- column-for-column, constraint-for-constraint against production.
--
-- This schema is NOT referenced anywhere in this repo's application code
-- (confirmed via grep). Its table shapes closely match two open,
-- unimplemented GitHub issues — #7 ("Build admin pickup-day assignment and
-- fulfillment workflow") and #12 ("Update fulfillment views, production
-- counts, and pack-list generation") — suggesting it was scaffolded ahead of
-- that work.
--
-- No RLS is enabled on any of these 4 tables in production today (confirmed
-- via Supabase advisors/list_tables at capture time). This migration
-- captures that as-is; it does not add RLS enabling statements that aren't
-- in the source.
-- =============================================================================

create schema if not exists production;

-- -----------------------------------------------------------------------------
-- Section 1: Tables
-- -----------------------------------------------------------------------------

CREATE TABLE production.equipment (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  equipment_type text NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT equipment_equipment_type_check CHECK (equipment_type = ANY (ARRAY['smoker'::text, 'grill'::text, 'griddle'::text, 'oven'::text, 'sous_vide'::text, 'other'::text])),
  CONSTRAINT equipment_name_key UNIQUE (name),
  CONSTRAINT equipment_pkey PRIMARY KEY (id)
);

CREATE TABLE production.production_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  production_date date NOT NULL,
  production_type text NOT NULL,
  reference_type text,
  reference_id bigint,
  status text DEFAULT 'planned'::text NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT production_runs_pkey PRIMARY KEY (id),
  CONSTRAINT production_runs_production_type_check CHECK (production_type = ANY (ARRAY['frozen_drop'::text, 'catering'::text, 'vending'::text, 'practice'::text, 'other'::text])),
  CONSTRAINT production_runs_reference_pair_check CHECK (reference_type IS NULL AND reference_id IS NULL OR reference_type IS NOT NULL AND reference_id IS NOT NULL),
  CONSTRAINT production_runs_status_check CHECK (status = ANY (ARRAY['planned'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text]))
);

CREATE TABLE production.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  sku text NOT NULL,
  product_type text DEFAULT 'finished_good'::text NOT NULL,
  unit text NOT NULL,
  target_yield_percent numeric(5,2),
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_product_type_check CHECK (product_type = ANY (ARRAY['finished_good'::text, 'raw_material'::text])),
  CONSTRAINT products_sku_key UNIQUE (sku),
  CONSTRAINT products_target_yield_percent_check CHECK (target_yield_percent IS NULL OR target_yield_percent >= 0::numeric AND target_yield_percent <= 100::numeric),
  CONSTRAINT products_unit_check CHECK (unit = ANY (ARRAY['lb'::text, 'oz'::text, 'each'::text, 'bag'::text, 'bottle'::text]))
);

CREATE TABLE production.production_cooks (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  production_run_id bigint NOT NULL,
  product_id bigint NOT NULL,
  equipment_id bigint,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  raw_weight_lb numeric(8,2) NOT NULL,
  finished_weight_lb numeric(8,2),
  waste_weight_lb numeric(8,2),
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT production_cooks_finished_weight_check CHECK (finished_weight_lb IS NULL OR finished_weight_lb <= raw_weight_lb),
  CONSTRAINT production_cooks_finished_weight_lb_check CHECK (finished_weight_lb IS NULL OR finished_weight_lb >= 0::numeric),
  CONSTRAINT production_cooks_pkey PRIMARY KEY (id),
  CONSTRAINT production_cooks_raw_weight_lb_check CHECK (raw_weight_lb > 0::numeric),
  CONSTRAINT production_cooks_time_check CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at),
  CONSTRAINT production_cooks_waste_weight_lb_check CHECK (waste_weight_lb IS NULL OR waste_weight_lb >= 0::numeric),
  CONSTRAINT production_cooks_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES production.equipment(id) ON DELETE SET NULL,
  CONSTRAINT production_cooks_product_id_fkey FOREIGN KEY (product_id) REFERENCES production.products(id) ON DELETE RESTRICT,
  CONSTRAINT production_cooks_production_run_id_fkey FOREIGN KEY (production_run_id) REFERENCES production.production_runs(id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Section 2: Indexes
-- -----------------------------------------------------------------------------

create index idx_production_cooks_equipment on production.production_cooks (equipment_id);
create index idx_production_cooks_product on production.production_cooks (product_id);
create index idx_production_cooks_run on production.production_cooks (production_run_id);
create index idx_production_cooks_started_at on production.production_cooks (started_at);
create index idx_production_runs_date on production.production_runs (production_date);
create index idx_production_runs_status on production.production_runs (status);
create index idx_production_runs_type on production.production_runs (production_type);
